steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/frontend', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/order-service', './services/order-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/product-service', './services/product-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/user-service', './services/user-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/order-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/product-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/user-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'frontend',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/frontend',
      '--platform', 'managed',
      '--region', '$_REGION',
      '--allow-unauthenticated'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'order-service',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/order-service',
      '--platform', 'managed',
      '--region', '$_REGION',
      '--allow-unauthenticated'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'product-service',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/product-service',
      '--platform', 'managed',
      '--region', '$_REGION',
      '--allow-unauthenticated'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'user-service',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/user-service',
      '--platform', 'managed',
      '--region', '$_REGION',
      '--allow-unauthenticated'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/frontend'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/order-service'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/product-service'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/e-commerce/user-service'

substitutions:
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
