options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://e-commerce-aitdevops

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-service', './services/order-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-service', './services/product-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-service', './services/user-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend', '--image', 'gcr.io/$PROJECT_ID/frontend', '--platform', 'managed', '--region', '$_REGION', '--allow-unauthenticated']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'order-service', '--image', 'gcr.io/$PROJECT_ID/order-service', '--platform', 'managed', '--region', '$_REGION', '--allow-unauthenticated']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'product-service', '--image', 'gcr.io/$PROJECT_ID/product-service', '--platform', 'managed', '--region', '$_REGION', '--allow-unauthenticated']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'user-service', '--image', 'gcr.io/$PROJECT_ID/user-service', '--platform', 'managed', '--region', '$_REGION', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/frontend'
  - 'gcr.io/$PROJECT_ID/order-service'
  - 'gcr.io/$PROJECT_ID/product-service'
  - 'gcr.io/$PROJECT_ID/user-service'

substitutions:
  _REGION: 'us-central1'
