name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'services/product-service/**'
      - 'services/order-service/**'
      - 'services/user-service/**'
      - 'frontend/**'
      - 'charts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        install_components: kubectl

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --zone ${{ secrets.CLUSTER_ZONE }} --project ${{ secrets.PROJECT_ID }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: Build and push frontend image
      if: contains(github.event.head_commit.message, 'frontend')
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/frontend:${{ env.IMAGE_TAG }} -f frontend/Dockerfile ./frontend
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/frontend:${{ env.IMAGE_TAG }}

    - name: Update Helm values file for frontend
      if: contains(github.event.head_commit.message, 'frontend')
      run: |
        sed -i 's/tag: ".*"/tag: "${{ env.IMAGE_TAG }}"/' charts/frontend/values.yaml

    - name: Deploy frontend with Helm
      if: contains(github.event.head_commit.message, 'frontend')
      run: |
        helm upgrade --install frontend charts/frontend --set image.tag=${{ env.IMAGE_TAG }}

    - name: Build and push product-service image
      if: contains(github.event.head_commit.message, 'product-service')
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/product-service:${{ env.IMAGE_TAG }} -f services/product-service/Dockerfile ./services/product-service
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/product-service:${{ env.IMAGE_TAG }}

    - name: Update Helm values file for product-service
      if: contains(github.event.head_commit.message, 'product-service')
      run: |
        sed -i 's/tag: ".*"/tag: "${{ env.IMAGE_TAG }}"/' charts/product-service/values.yaml

    - name: Deploy product-service with Helm
      if: contains(github.event.head_commit.message, 'product-service')
      run: |
        helm upgrade --install product-service charts/product-service --set image.tag=${{ env.IMAGE_TAG }}

    - name: Build and push order-service image
      if: contains(github.event.head_commit.message, 'order-service')
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/order-service:${{ env.IMAGE_TAG }} -f services/order-service/Dockerfile ./services/order-service
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/order-service:${{ env.IMAGE_TAG }}

    - name: Update Helm values file for order-service
      if: contains(github.event.head_commit.message, 'order-service')
      run: |
        sed -i 's/tag: ".*"/tag: "${{ env.IMAGE_TAG }}"/' charts/order-service/values.yaml

    - name: Deploy order-service with Helm
      if: contains(github.event.head_commit.message, 'order-service')
      run: |
        helm upgrade --install order-service charts/order-service --set image.tag=${{ env.IMAGE_TAG }}

    - name: Build and push user-service image
      if: contains(github.event.head_commit.message, 'user-service')
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/user-service:${{ env.IMAGE_TAG }} -f services/user-service/Dockerfile ./services/user-service
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/user-service:${{ env.IMAGE_TAG }}

    - name: Update Helm values file for user-service
      if: contains(github.event.head_commit.message, 'user-service')
      run: |
        sed -i 's/tag: ".*"/tag: "${{ env.IMAGE_TAG }}"/' charts/user-service/values.yaml

    - name: Deploy user-service with Helm
      if: contains(github.event.head_commit.message, 'user-service')
      run: |
        helm upgrade --install user-service charts/user-service --set image.tag=${{ env.IMAGE_TAG }}

    - name: Print Helm Release History for frontend
      run: |
        helm history frontend

    - name: Print Helm Release History for product-service
      run: |
        helm history product-service

    - name: Print Helm Release History for order-service
      run: |
        helm history order-service

    - name: Print Helm Release History for user-service
      run: |
        helm history user-service
