name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Ensure this matches your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        install_components: 'kubectl'

    - name: Configure Docker
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: Build and push Docker images
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/frontend:latest -f frontend/Dockerfile ./frontend
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/product-service:latest -f services/product-service/Dockerfile ./services/product-service
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/order-service:latest -f services/order-service/Dockerfile ./services/order-service
        docker build -t us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/user-service:latest -f services/user-service/Dockerfile ./services/user-service
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/frontend:latest
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/product-service:latest
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/order-service:latest
        docker push us-docker.pkg.dev/${{ secrets.PROJECT_ID }}/company-y/aitdevops8/user-service:latest

    - name: Deploy to GKE
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        CLUSTER_ZONE: ${{ secrets.CLUSTER_ZONE }}
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID
        kubectl set image deployment/frontend frontend=us-docker.pkg.dev/$PROJECT_ID/company-y/aitdevops8/frontend:latest
        kubectl set image deployment/product-service product-service=us-docker.pkg.dev/$PROJECT_ID/company-y/aitdevops8/product-service:latest
        kubectl set image deployment/order-service order-service=us-docker.pkg.dev/$PROJECT_ID/company-y/aitdevops8/order-service:latest
        kubectl set image deployment/user-service user-service=us-docker.pkg.dev/$PROJECT_ID/company-y/aitdevops8/user-service:latest
